// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.1
// source: wallet/wallet.proto

package wallet

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletReq) Reset() {
	*x = CreateWalletReq{}
	mi := &file_wallet_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletReq) ProtoMessage() {}

func (x *CreateWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletReq.ProtoReflect.Descriptor instead.
func (*CreateWalletReq) Descriptor() ([]byte, []int) {
	return file_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=walletId,proto3" json:"walletId,omitempty"` // 唯一钱包id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_wallet_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWalletResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CreateWalletResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *CreateWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type QueryWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=walletId,proto3" json:"walletId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWalletReq) Reset() {
	*x = QueryWalletReq{}
	mi := &file_wallet_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWalletReq) ProtoMessage() {}

func (x *QueryWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWalletReq.ProtoReflect.Descriptor instead.
func (*QueryWalletReq) Descriptor() ([]byte, []int) {
	return file_wallet_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *QueryWalletReq) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type QueryWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=walletId,proto3" json:"walletId,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryWalletResponse) Reset() {
	*x = QueryWalletResponse{}
	mi := &file_wallet_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryWalletResponse) ProtoMessage() {}

func (x *QueryWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryWalletResponse.ProtoReflect.Descriptor instead.
func (*QueryWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *QueryWalletResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *QueryWalletResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *QueryWalletResponse) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *QueryWalletResponse) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type TransferWalletReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrcWalletId   string                 `protobuf:"bytes,1,opt,name=srcWalletId,proto3" json:"srcWalletId,omitempty"`
	DestWalletId  string                 `protobuf:"bytes,2,opt,name=destWalletId,proto3" json:"destWalletId,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferWalletReq) Reset() {
	*x = TransferWalletReq{}
	mi := &file_wallet_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferWalletReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferWalletReq) ProtoMessage() {}

func (x *TransferWalletReq) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferWalletReq.ProtoReflect.Descriptor instead.
func (*TransferWalletReq) Descriptor() ([]byte, []int) {
	return file_wallet_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *TransferWalletReq) GetSrcWalletId() string {
	if x != nil {
		return x.SrcWalletId
	}
	return ""
}

func (x *TransferWalletReq) GetDestWalletId() string {
	if x != nil {
		return x.DestWalletId
	}
	return ""
}

func (x *TransferWalletReq) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type TransferWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int64                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrMsg        string                 `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferWalletResponse) Reset() {
	*x = TransferWalletResponse{}
	mi := &file_wallet_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferWalletResponse) ProtoMessage() {}

func (x *TransferWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wallet_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferWalletResponse.ProtoReflect.Descriptor instead.
func (*TransferWalletResponse) Descriptor() ([]byte, []int) {
	return file_wallet_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *TransferWalletResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TransferWalletResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_wallet_wallet_proto protoreflect.FileDescriptor

const file_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	"\x13wallet/wallet.proto\x12\x06wallet\x1a\x1cgoogle/api/annotations.proto\"\x11\n" +
	"\x0fCreateWalletReq\"c\n" +
	"\x14CreateWalletResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12\x1a\n" +
	"\bwalletId\x18\x03 \x01(\tR\bwalletId\",\n" +
	"\x0eQueryWalletReq\x12\x1a\n" +
	"\bwalletId\x18\x01 \x01(\tR\bwalletId\"|\n" +
	"\x13QueryWalletResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg\x12\x1a\n" +
	"\bwalletId\x18\x03 \x01(\tR\bwalletId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\"s\n" +
	"\x11TransferWalletReq\x12 \n" +
	"\vsrcWalletId\x18\x01 \x01(\tR\vsrcWalletId\x12\"\n" +
	"\fdestWalletId\x18\x02 \x01(\tR\fdestWalletId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\"I\n" +
	"\x16TransferWalletResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x03R\x06result\x12\x17\n" +
	"\aerr_msg\x18\x02 \x01(\tR\x06errMsg2\xc7\x02\n" +
	"\rWalletService\x12\\\n" +
	"\x0eGenerateWallet\x12\x17.wallet.CreateWalletReq\x1a\x1c.wallet.CreateWalletResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/wallets\x12f\n" +
	"\x12QueryWalletBalance\x12\x16.wallet.QueryWalletReq\x1a\x1b.wallet.QueryWalletResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/wallets/{walletId}\x12p\n" +
	"\x15TransferWalletBalance\x12\x19.wallet.TransferWalletReq\x1a\x1e.wallet.TransferWalletResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/wallets/transferB\vZ\t./;walletb\x06proto3"

var (
	file_wallet_wallet_proto_rawDescOnce sync.Once
	file_wallet_wallet_proto_rawDescData []byte
)

func file_wallet_wallet_proto_rawDescGZIP() []byte {
	file_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wallet_wallet_proto_rawDesc), len(file_wallet_wallet_proto_rawDesc)))
	})
	return file_wallet_wallet_proto_rawDescData
}

var file_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_wallet_wallet_proto_goTypes = []any{
	(*CreateWalletReq)(nil),        // 0: wallet.CreateWalletReq
	(*CreateWalletResponse)(nil),   // 1: wallet.CreateWalletResponse
	(*QueryWalletReq)(nil),         // 2: wallet.QueryWalletReq
	(*QueryWalletResponse)(nil),    // 3: wallet.QueryWalletResponse
	(*TransferWalletReq)(nil),      // 4: wallet.TransferWalletReq
	(*TransferWalletResponse)(nil), // 5: wallet.TransferWalletResponse
}
var file_wallet_wallet_proto_depIdxs = []int32{
	0, // 0: wallet.WalletService.GenerateWallet:input_type -> wallet.CreateWalletReq
	2, // 1: wallet.WalletService.QueryWalletBalance:input_type -> wallet.QueryWalletReq
	4, // 2: wallet.WalletService.TransferWalletBalance:input_type -> wallet.TransferWalletReq
	1, // 3: wallet.WalletService.GenerateWallet:output_type -> wallet.CreateWalletResponse
	3, // 4: wallet.WalletService.QueryWalletBalance:output_type -> wallet.QueryWalletResponse
	5, // 5: wallet.WalletService.TransferWalletBalance:output_type -> wallet.TransferWalletResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wallet_wallet_proto_init() }
func file_wallet_wallet_proto_init() {
	if File_wallet_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wallet_wallet_proto_rawDesc), len(file_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_wallet_wallet_proto_depIdxs,
		MessageInfos:      file_wallet_wallet_proto_msgTypes,
	}.Build()
	File_wallet_wallet_proto = out.File
	file_wallet_wallet_proto_goTypes = nil
	file_wallet_wallet_proto_depIdxs = nil
}
